

	ComponentComment ("Dispatch file for OpenGLCodec")

	ComponentSelectorOffset (-kComponentGetMPWorkFunctionSelect)

	ComponentRangeCount	(4)
	ComponentRangeShift	(8)
	ComponentRangeMask	(FF)

	ComponentRangeBegin (0)
/*		StdComponentCall  (GetMPWorkFunction) */
		ComponentError    (GetMPWorkFunction)
		ComponentError	  (Unregister)
		StdComponentCall  (Target)
		StdComponentCall  (Register)
		StdComponentCall  (Version)
		StdComponentCall  (CanDo)
		StdComponentCall  (Close)
		StdComponentCall  (Open)
	ComponentRangeEnd	(0)
	
	ComponentRangeBegin (1)
		ComponentCall	  (GetCodecInfo)

		ComponentDelegate (GetCompressionTime)
		ComponentDelegate (GetMaxCompressionSize)
		ComponentDelegate (PreCompress)
		ComponentDelegate (BandCompress)
		ComponentDelegate (PreDecompress)
		ComponentDelegate (BandDecompress)
		ComponentDelegate (Busy)
		ComponentDelegate (GetCompressedImageSize)
		ComponentDelegate (GetSimilarity)
		ComponentDelegate (TrimImage)
		ComponentDelegate (RequestSettings)
		ComponentDelegate (GetSettings)
		ComponentDelegate (SetSettings)
		ComponentDelegate (Flush)
		ComponentDelegate (SetTimeCode)
		ComponentDelegate (IsImageDescriptionEquivalent)
		ComponentDelegate (NewMemory)
		ComponentDelegate (DisposeMemory)
		ComponentDelegate (HitTestData)
		ComponentDelegate (NewImageBufferMemory)
		ComponentDelegate (ExtractAndCombineFields)
		ComponentDelegate (GetMaxCompressionSizeWithSources)
		ComponentDelegate (SetTimeBase)
		ComponentDelegate (SourceChanged)
		ComponentDelegate (FlushFrame)
		ComponentDelegate (GetSettingsAsText)
		ComponentDelegate (GetParameterListHandle)
		ComponentDelegate (GetParameterList)
		ComponentDelegate (CreateStandardParameterDialog)
		ComponentDelegate (IsStandardParameterDialogEvent)
		ComponentDelegate (DismissStandardParameterDialog)
		ComponentDelegate (StandardParameterDialogDoAction)

		ComponentCall	  (NewImageGWorld)
		ComponentCall	  (DisposeImageGWorld)

		ComponentDelegate (HitTestDataWithFlags)
		ComponentDelegate (ValidateParameters)
		ComponentDelegate (GetBaseMPWorkFunction)
		
		ComponentCall     (LockBits)
		ComponentCall     (UnlockBits)
		
		ComponentDelegate (RequestGammaLevel)
		ComponentDelegate (GetSourceDataGammaLevel)
		ComponentDelegate (GetDecompressLatency)
	ComponentRangeEnd	(1)

	ComponentComment ("SubType range, eg. JPEG")
	ComponentRangeUnused (2)

	ComponentComment ("Base Range")
	ComponentRangeBegin	(3)
		ComponentCall  (Preflight)
		ComponentCall  (Initialize)
		ComponentCall  (BeginBand)
		ComponentCall  (DrawBand)
		ComponentNoError  (EndBand)
		ComponentNoError  (QueueStarting)
		ComponentNoError  (QueueStopping)
		
		ComponentError (DroppingFrame)
		ComponentError (ScheduleFrame)
		ComponentError (CancelTrigger)
	ComponentRangeEnd	(3)

	ComponentComment ("Effect Range")
	ComponentRangeUnused (4)